FROM node:latest

WORKDIR /app
COPY ./administration-app/package.json ./
RUN npm install --legacy-peer-deps

COPY ./administration-app ./

RUN npm run build --production
RUN npm install -g serve

EXPOSE 80

#CMD [ "npm", "start" ]
CMD serve -s build -p 80
