FROM node:latest

WORKDIR /app
COPY ./package.json ./
RUN npm install --legacy-peer-deps

COPY ./ .


RUN npm i webpack@5.82.0 --legacy-peer-deps

RUN npm run build --production
RUN npm install -g serve

EXPOSE 80

#CMD [ "npm", "start" ]
CMD serve -s build -p 80
